name: Build with Gradle

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Archive artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: "Build artifacts"
          path: "build/libs/VelocityPermissionsWhitelist-*.jar"
          if-no-files-found: error

